name: 'Bug Report'
description: "Something isn't working as expected."
title: '[Bug] '
labels: ['type: bug', 'status: triage', 'in: game']
projects: ['Alpha-Blend-Interactive/2']

body:

  - type: markdown
    attributes:
      value: |
        # Checklist

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      description: |
        Please make sure you've followed all steps before submitting.
        🔗 [How to properly disable mods](https://github.com/ChilloutVR-Team/ChilloutVR-Issues/?tab=readme-ov-file#how-to-properly-disable-mods){:target="_blank"}
      options:
        - label: '(If using Mods) I ensured the issue occurred without using mods by renaming version.dll to version.dll.disabled'
          required: true
        - label: 'I checked that no other Bug Report describing my problem exists.'
          required: true
        - label: 'I accept that this issue may be closed if any of the above are found to be untrue.'
          required: true

  - type: markdown
    attributes:
      value: |
        # System Information

  - type: input
    id: platform
    attributes:
      label: Platform
      description: What platform are you using?
      placeholder: 'E.g.: Steam PC, Meta Quest, Pico, ..'
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What Operating System are you using? If possible, please include the release version.
      placeholder: 'E.g.: Windows 10, Windows 11, Windows 11 24H2, ..'
    validations:
      required: True

  - type: markdown
    attributes:
      value: |
        # ChilloutVR Information

  - type: input
    id: game-version
    attributes:
      label: 'Game Version'
      description: What game version are you using? (You can find this in the main menu of the game)
      placeholder: 'E.g.: 2025r178, ..'
    validations:
      required: true

  - type: dropdown
    id: branch
    attributes:
      label: Branch
      description: What branch of the game did this happen on?
      options:
        - Stable (Default branch, use this if unsure)
        - Nightly
        - Other (Leave as remark)
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # What happened?

  - type: textarea
    id: what-happened
    attributes:
      label: 'Describe what happened as precisely as possible.'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # What did you expect to happen?

  - type: textarea
    id: what-did-you-expect
    attributes:
      label: 'Describe what you expected to happen instead.'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Steps to reproduce

  - type: input
    id: how-to-reproduce-content
    attributes:
      label: Content GUID
      description: 'Please provide us with an ingame content guid. Make sure to prefix it with `a+` for avatars, `p+` for props, `w+` for worlds. You can copy the ID of something by double clicking its picture. Note that your content **can** be private and does not need to be public.'
    validations:
      required: false

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: 'In as much detail as possible, describe the exact steps you took to make the problem appear.'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Anything else?

  - type: textarea
    id: anything-else
    attributes:
      label: 'Other remarks'
    validations:
      required: false
