name: 'CCK Feature Enhancement / Addition'
description: "You have a suggestion for an enhancement or addition to an existing feature?"
title: '[CCK Feature Enhancement] '
labels: ['type: enhancement', 'status: triage', 'in: cck']
projects: ['Alpha-Blend-Interactive/2']

body:

  - type: markdown
    attributes:
      value: |
        # Checklist

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: 'I checked that there is no other Enhancement or Feature Request describing my wish.'
          required: true
        - label: 'I checked that this part of the feature is, in fact, not supported.'
          required: true
        - label: 'I accept that this issue may be closed if any of the above are found to be untrue.'
          required: true

  - type: markdown
    attributes:
      value: |
        # Whats the core feature?

  - type: textarea
    id: feature
    attributes:
      label: 'Whats the core feature this is about?'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Describe the feature

  - type: textarea
    id: feature-addition
    attributes:
      label: 'What should be possible that currently is not with this feature? (What should be added?)'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Anything else?

  - type: textarea
    id: anything-else
    attributes:
      label: 'Other remarks'
    validations:
      required: false
